const DATA = window.EXAM_DATA;
let state = {paper: DATA.papers[0].id, group: DATA.papers[0].groups[0].id, index:0, selected:null, marked:false, answers:{}, mistakes:[]};
function paper(){return DATA.papers.find(p=>p.id===state.paper)}
function group(){return paper().groups.find(g=>g.id===state.group)}
function questions(){return group().questions}
function current(){return questions()[state.index]}
function shuffle(arr, seed){let a=[...arr];let x=seed.split('').reduce((s,c)=>s+c.charCodeAt(0),0)||1; for(let i=a.length-1;i>0;i--){x=(x*9301+49297)%233280; let j=Math.floor((x/233280)*(i+1)); [a[i],a[j]]=[a[j],a[i]];} return a}
function key(q){return state.paper+'|'+q.id}
function renderTabs(){const el=document.getElementById('paperTabs');el.innerHTML='';DATA.papers.forEach(p=>{let b=document.createElement('button');b.textContent=p.title;b.className=p.id===state.paper?'active':'';b.onclick=()=>{state.paper=p.id;state.group=p.groups[0].id;state.index=0;state.selected=null;state.marked=false;renderAll()};el.appendChild(b)});}
function renderGroups(){document.getElementById('paperTitle').textContent=paper().title;const pdfLink=document.getElementById('pdfLink');pdfLink.href=paper().pdf; const list=document.getElementById('questionGroups');list.innerHTML='';paper().groups.forEach(g=>{let btn=document.createElement('button');btn.className='group-btn '+(g.id===state.group?'active':'');btn.innerHTML=`<strong>${g.title}</strong><span>${g.topic}</span><span class="mini">${g.questions.length} MCQs</span>`;btn.onclick=()=>{state.group=g.id;state.index=0;state.selected=null;state.marked=false;renderAll()};list.appendChild(btn)});}
function renderPdf(page){let src=paper().pdf; if(page){src += '#page='+page;} document.getElementById('pdfFrame').src=src; document.getElementById('pdfHint').textContent=page?`Opened near page ${page}.`:'Use the PDF to compare the original wording and diagrams.';}
function renderQuestion(){const area=document.getElementById('questionArea');const q=current();const k=key(q);const saved=state.answers[k];state.selected=saved?.selected ?? null;state.marked=!!saved?.marked;const shuffled = saved?.shuffled || shuffle(q.options.map((o,i)=>({o,i})),q.id); if(!saved){state.answers[k]={shuffled, selected:null, marked:false}}
let html=`<div class="progress">${paper().title} / ${group().title} / Question ${state.index+1} of ${questions().length}</div><div class="q-meta"><span class="badge">${group().topic}</span>${q.page?`<span class="badge">PDF page ${q.page}</span>`:''}</div><h2 class="q-title">${q.text}</h2><div class="options">`;
shuffled.forEach((opt,displayIndex)=>{let cls='option'; if(state.selected===displayIndex) cls+=' selected'; if(state.marked){cls+=' locked'; if(opt.i===q.answer) cls+=' correct'; if(state.selected===displayIndex && opt.i!==q.answer) cls+=' wrong';}
html+=`<button class="${cls}" data-idx="${displayIndex}"><strong>${String.fromCharCode(65+displayIndex)}.</strong> ${opt.o}</button>`});
html+='</div><div class="controls">';
html+=`<button class="primary" id="markBtn" ${state.selected===null||state.marked?'disabled':''}>Mark</button>`;
html+=`<button class="secondary" id="nextBtn">${state.index===questions().length-1?'Finish group':'Next question'}</button>`;
html+=`<button class="ghost" id="pdfBtn">View source PDF</button>`;
html+='</div>';
if(state.marked){let correct=shuffled.find(o=>o.i===q.answer).o;let chosen=state.selected!==null?shuffled[state.selected].o:'No answer';let ok=shuffled[state.selected]?.i===q.answer;html+=`<div class="feedback"><strong>${ok?'Correct':'Not quite'}</strong><p>Your answer: ${chosen}</p><p>Correct answer: ${correct}</p><p>${q.explanation}</p><div class="fact"><strong>OCR fact</strong>${q.fact}</div></div>`}
area.innerHTML=html;area.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{if(state.marked)return;state.selected=Number(btn.dataset.idx);state.answers[k].selected=state.selected;renderQuestion();updateScore();});document.getElementById('markBtn').onclick=mark;document.getElementById('nextBtn').onclick=next;document.getElementById('pdfBtn').onclick=()=>renderPdf(q.page);renderPdf(q.page);}
function mark(){const q=current();const k=key(q);state.marked=true;state.answers[k].marked=true;const sel=state.answers[k].shuffled[state.selected];if(sel.i!==q.answer && !state.mistakes.includes(k)) state.mistakes.push(k);if(sel.i===q.answer) state.mistakes=state.mistakes.filter(x=>x!==k);renderQuestion();updateScore();}
function next(){if(state.index<questions().length-1){state.index++;state.selected=null;state.marked=false;renderQuestion()}else{renderSummary()}}
function updateScore(){let total=0,score=0;DATA.papers.forEach(p=>p.groups.forEach(g=>g.questions.forEach(q=>{const a=state.answers[p.id+'|'+q.id]; if(a?.marked){total++; let selected=a.shuffled[a.selected]; if(selected?.i===q.answer)score++;}})));document.getElementById('scorePill').textContent=`Score: ${score} / ${total}`;}
function renderSummary(){const area=document.getElementById('questionArea');const qs=questions();let done=0,score=0;qs.forEach(q=>{let a=state.answers[key(q)];if(a?.marked){done++; if(a.shuffled[a.selected]?.i===q.answer)score++;}});area.innerHTML=`<div class="q-meta"><span class="badge">Group complete</span></div><h2>${group().title}</h2><p>You scored <strong>${score} / ${done}</strong> for this group.</p><div class="controls"><button class="primary" id="againBtn">Restart this group</button><button class="secondary" id="reviewLocal">Review mistakes</button></div>`;document.getElementById('againBtn').onclick=()=>{qs.forEach(q=>delete state.answers[key(q)]);state.mistakes=state.mistakes.filter(k=>!qs.some(q=>key(q)===k));state.index=0;state.selected=null;state.marked=false;renderQuestion();updateScore();};document.getElementById('reviewLocal').onclick=renderReview;}
function renderReview(){const area=document.getElementById('questionArea');let items=[];DATA.papers.forEach(p=>p.groups.forEach(g=>g.questions.forEach(q=>{let k=p.id+'|'+q.id;let a=state.answers[k]; if(a?.marked && a.shuffled[a.selected]?.i!==q.answer){items.push({p,g,q,a,k})}})));if(items.length===0){area.innerHTML='<div class="empty"><h2>No mistakes to review yet</h2><p>When a question is marked incorrect, it will appear here with the correct answer and an OCR fact.</p></div>';return}
let html='<h2>Review mistakes</h2><p>Use this list for targeted revision. Each item includes the correct answer and a short OCR fact.</p><div class="review-list">';items.forEach(it=>{let chosen=it.a.shuffled[it.a.selected]?.o||'No answer';let correct=it.q.options[it.q.answer];html+=`<article class="review-item"><h3>${it.p.title} – ${it.g.title}</h3><p><strong>Question:</strong> ${it.q.text}</p><p><strong>Your answer:</strong> ${chosen}</p><p><strong>Correct answer:</strong> ${correct}</p><p><strong>Explanation:</strong> ${it.q.explanation}</p><div class="fact"><strong>OCR fact</strong>${it.q.fact}</div><p><a href="${it.p.pdf}${it.q.page?'#page='+it.q.page:''}" target="_blank">View source PDF</a></p></article>`});html+='</div>';area.innerHTML=html;}
function resetPaper(){paper().groups.forEach(g=>g.questions.forEach(q=>delete state.answers[state.paper+'|'+q.id]));state.mistakes=state.mistakes.filter(k=>!k.startsWith(state.paper+'|'));state.index=0;state.selected=null;state.marked=false;renderAll();updateScore();}
function renderAll(){renderTabs();renderGroups();renderQuestion();updateScore();}
document.getElementById('reviewBtn').onclick=renderReview;document.getElementById('resetBtn').onclick=resetPaper;renderAll();
