window.CODING_DATA = {
  papers: [
    {
      id: '2025', title: 'H446/01 June 2025', pdf: 'pdfs/H44601 Computer systems June 2025.pdf',
      questions: [
        {id:'25-lmc-outputs', topic:'Q1 – LMC Fibonacci trace', page:3, skill:'Trace LMC output',
          code:`START LDA MAX\nBRZ END\nLDA A\nOUT\nADD B\nSTA B\nLDA B\nSTA A\nLDA MAX\nSUB ONE\nSTA MAX\nBRA START\nEND HLT\nA DAT 0\nB DAT 1\nMAX DAT 5\nONE DAT 1`,
          question:'The program is intended to output the first five Fibonacci values, but it contains an error. What five values are actually output?',
          options:['0, 1, 1, 2, 3','0, 1, 2, 4, 8','1, 1, 2, 3, 5','0, 0, 1, 1, 2'], answer:1,
          worked:['A starts at 0 and B starts at 1.','The program outputs A first.','It then adds B to A and stores the result in B.','It then copies B into A, causing the value to double each cycle after the first output.','The outputs are 0, 1, 2, 4, 8.'],
          fact:'When tracing LMC, track the accumulator and each DAT value after every STA.'},
        {id:'25-lmc-temp', topic:'Q1 – Fixing LMC with temporary storage', page:4, skill:'Choose missing LMC line',
          code:`LDA A\nOUT\n_____\nSTA TEMP\nLDA A\nADD B\nSTA B\n_____\nSTA A\n...\nA DAT 0\nB DAT 1\nTEMP DAT 0`,
          question:'Why does the corrected Fibonacci version need TEMP?',
          options:['To store MAX while the loop counts down','To keep the old value of B before B is overwritten','To store the output permanently','To make BRZ work correctly'], answer:1,
          worked:['The Fibonacci update needs old A and old B.','B is changed to A + B.','A must then become the old B, not the new B.','TEMP stores the old B while B is being updated.'],
          fact:'A temporary variable is often used when one value would otherwise be overwritten before it is reused.'},
        {id:'25-sql-insert', topic:'Q6 – SQL INSERT', page:18, skill:'Read SQL structure',
          code:`TblSoftware(ProductID, Name, Type, Price)\n\nNew product:\nProductID: DCC07\nName: DCCCast\nType: Sound\nPrice: 89.99`,
          question:'Which SQL statement correctly inserts the new product?',
          options:[`INSERT INTO TblSoftware VALUES ("DCC07", "DCCCast", "Sound", 89.99)`,`SELECT INTO TblSoftware VALUES ("DCC07", "DCCCast", "Sound", 89.99)`,`INSERT TblSoftware ("DCC07", "DCCCast", "Sound", 89.99)`,`UPDATE TblSoftware SET ProductID="DCC07"`], answer:0,
          worked:['INSERT INTO names the table.','VALUES provides the new row values in the correct field order.','SELECT is for retrieving data, not inserting a new record.'],
          fact:'OCR SQL questions expect exact table and field names where they are provided.'},
        {id:'25-sql-nested', topic:'Q6 – Nested SELECT', page:19, skill:'Interpret nested SQL',
          code:`SELECT Name FROM TblSoftware\nWHERE Price < (\n  SELECT Price FROM TblSoftware\n  WHERE Name = "DCCDraw"\n)`,
          question:'What is the purpose of the nested SELECT?',
          options:['It deletes DCCDraw from the table','It finds the price of DCCDraw so the outer query can compare against it','It returns all products called DCCDraw only','It changes all prices to match DCCDraw'], answer:1,
          worked:['The inner SELECT runs first.','It returns the price of the product named DCCDraw.','The outer query returns products with a lower price than that value.'],
          fact:'A nested SELECT is often used when a query needs to compare with a value found by another query.'},
        {id:'25-js-checkanswers', topic:'Q8 – JavaScript function completion', page:25, skill:'Read loop and array index',
          code:`function checkAnswers(responses, feedbacks, answers) {\n  var score = 0;\n  for(var qCount = 0; qCount < responses.length; qCount++) {\n    response = document.getElementById(responses[qCount]).innerHTML;\n    answer = answers[qCount];\n    feedbackElement = document.getElementById(feedbacks[qCount]);\n    if (response == answer) {\n      score = score + 1;\n      feedbackElement.innerHTML = "Correct";\n    }\n  }\n  return score;\n}`,
          question:'Why is answers[qCount] used inside the loop?',
          options:['It always selects the first answer','It selects the matching correct answer for the current question number','It changes the answer array','It stops the loop'], answer:1,
          worked:['qCount is the loop counter.','responses[qCount], feedbacks[qCount] and answers[qCount] refer to matching positions.','This keeps the user response and correct answer aligned.'],
          fact:'When parallel arrays are used, the same index is used to access related values.'},
        {id:'25-js-score', topic:'Q8 – Client-side score calculation', page:25, skill:'Trace variable update',
          code:`score = 0\nif (response == answer) {\n  score = score + 1\n  feedbackElement.innerHTML = "Correct"\n}`,
          question:'If three responses are checked and two are correct, what final score is returned?',
          options:['0','1','2','3'], answer:2,
          worked:['score starts at 0.','Each correct answer adds 1.','Two correct answers means score becomes 2.'],
          fact:'A counter variable is usually initialised before a loop and incremented when a condition is met.'},
        {id:'25-html-fulladder', topic:'Q5 – Logic from code-like structure', page:15, skill:'Read logic behaviour',
          code:`Full adder inputs: A, B, C(in)\nSum uses XOR logic.\nC(out) is true when at least two inputs are 1.`,
          question:'For A=1, B=1 and C(in)=0, what are Sum and C(out)?',
          options:['Sum=0, C(out)=1','Sum=1, C(out)=0','Sum=1, C(out)=1','Sum=0, C(out)=0'], answer:0,
          worked:['1 + 1 + 0 gives binary 10.','The Sum bit is 0.','The carry out is 1.'],
          fact:'A full adder adds three bits: A, B and carry in.'},
        {id:'25-binary-shift', topic:'Q3 – Bitwise operations', page:9, skill:'Apply bit shift',
          code:`positiveBinary >> 3`,
          question:'What is the effect of shifting a positive binary integer right by 3 places?',
          options:['Multiplies it by 3','Divides it by 3','Divides it by 8','Multiplies it by 8'], answer:2,
          worked:['A right shift divides by powers of 2.','Three places means divide by 2³.','2³ = 8.'],
          fact:'Left shifts multiply by powers of 2; right shifts divide by powers of 2 for positive integers.'}
      ]
    },
    {
      id: '2024', title: 'H446/01 June 2024', pdf: 'pdfs/H44601 Computer systems June 2024.pdf',
      questions: [
        {id:'24-lmc-reset', topic:'Q1 – LMC reset code', page:2, skill:'Choose LMC sequence',
          code:`total DAT ?\nzero DAT 0`,
          question:'Which LMC sequence resets total to 0 and stops?',
          options:[`LDA zero\nSTA total\nHLT`,`STA zero\nLDA total\nHLT`,`LDA total\nHLT\nSTA total`,`BRZ total\nHLT`], answer:0,
          worked:['LDA zero loads 0 into the accumulator.','STA total stores the accumulator into total.','HLT stops the program.'],
          fact:'In LMC, STA copies the accumulator value into a labelled memory location.'},
        {id:'24-class-video', topic:'Q2 – Class constructor', page:12, skill:'Read OOP constructor',
          code:`class video\n  private name\n  private views\n  private rating\n  public procedure new(newName)\n    name = newName\n    views = 0\n    rating = 3\n  endprocedure\nendclass`,
          question:'What values are set when new video("Intro") is created?',
          options:['name="Intro", views=0, rating=3','name="video", views=3, rating=0','name is blank, views=0, rating=0','name="Intro", views=3, rating=3'], answer:0,
          worked:['The constructor receives the parameter newName.','name is assigned the parameter value.','views is initialised to 0 and rating to 3.'],
          fact:'A constructor sets up a new object when it is instantiated.'},
        {id:'24-updateviews', topic:'Q2 – Method update', page:13, skill:'Trace method call',
          code:`public procedure updateviews()\n  views = views + 1\nendprocedure`,
          question:'If views is 7 before updateviews() is called, what is views afterwards?',
          options:['0','1','7','8'], answer:3,
          worked:['The method adds 1 to the current value.','7 + 1 = 8.'],
          fact:'An increment operation increases a variable by a fixed amount, usually 1.'},
        {id:'24-countcaps-condition', topic:'Q5 – ASCII condition', page:21, skill:'Complete condition',
          code:`if asc(c) >= 65 ______ then\n  capCount = capCount + 1\nendif`,
          question:'Which condition correctly checks that c is a capital letter A–Z?',
          options:['and asc(c) <= 90','or asc(c) <= 90','and asc(c) >= 90','or asc(c) == 65'], answer:0,
          worked:['Capital letters are ASCII 65 to 90 inclusive.','The character must be at least 65 and at most 90.','AND is needed because both conditions must be true.'],
          fact:'Inclusive range checks normally use >= lowerBound AND <= upperBound.'},
        {id:'24-countcaps-return', topic:'Q5 – Function return', page:21, skill:'Read return value',
          code:`function countCapitals(text)\n  capCount = 0\n  for x = 0 to text.length-1\n    c = text.subString(x, 1)\n    if asc(c) >= 65 and asc(c) <= 90 then\n      capCount = capCount + 1\n    endif\n  next x\n  return capCount\nendfunction`,
          question:'What does countCapitals("Hi AI") return?',
          options:['1','2','3','5'], answer:2,
          worked:['The capital letters are H, A and I.','Lowercase i is not counted.','Spaces are not counted.','The function returns 3.'],
          fact:'Trace string functions carefully: substring(x,1) reads one character at position x.'},
        {id:'24-mystery', topic:'Q5 – Mystery function trace', page:18, skill:'Trace return',
          code:`function mystery(a, b)\n  if a == 0 then\n    return b\n  elseif b == 0 then\n    return a\n  else\n    return a + b + a\n  endif\nendfunction`,
          question:'Using this style of branching, which path runs when the first condition is true?',
          options:['Only the first return path runs','All return paths run','The final else always runs','The function returns nothing'], answer:0,
          worked:['An if / elseif / else chain selects one branch.','Once a return statement is executed, the function ends.','Later branches are skipped.'],
          fact:'A return statement immediately exits a function.'},
        {id:'24-sql-adverts', topic:'Q2 – SQL with joined tables', page:8, skill:'Read SQL JOIN need',
          code:`Membership(Username, FirstName, StartDate, PackageType)\nPackage(PackageType, CostPerMonth, Adverts)`,
          question:'Why is a JOIN needed to find usernames of customers who see adverts?',
          options:['Username is in Membership but Adverts is in Package','Both fields are in the same table','JOIN is needed for every SELECT query','JOIN deletes adverts first'], answer:0,
          worked:['Username and FirstName are stored in Membership.','Adverts is stored in Package.','PackageType links the two tables.'],
          fact:'A foreign key lets data in one table refer to the primary key in another table.'},
        {id:'24-compiler-table', topic:'Q5 – Compilation stages', page:20, skill:'Match compiler stage',
          code:`Comments and whitespace are removed\nKeywords are replaced with tokens\nSymbol table is created`,
          question:'Which compilation stage does this describe?',
          options:['Lexical analysis','Syntax analysis','Code generation','Code optimisation'], answer:0,
          worked:['Lexical analysis breaks source code into tokens.','It removes whitespace/comments that are not needed.','It can also create the symbol table.'],
          fact:'Syntax analysis checks grammar and builds an abstract syntax tree.'}
      ]
    },
    {
      id: '2023', title: 'H446/01 June 2023', pdf: 'pdfs/H44601 Computer Systems June 2023.pdf',
      questions: [
        {id:'23-docheck', topic:'Q5 – Function trace', page:20, skill:'Trace digit algorithm',
          code:`function doCheck(number)\n  temp = str(number)\n  max = temp.length - 1\n  total = 0\n  for x = 0 to max\n    total = total + int(temp.subString(x,1))\n  next x\n  return total MOD 10\nendfunction`,
          question:'What is returned by doCheck(3178)?',
          options:['3','7','9','19'], answer:2,
          worked:['The digits are 3, 1, 7 and 8.','3 + 1 + 7 + 8 = 19.','19 MOD 10 = 9.'],
          fact:'MOD returns the remainder after integer division.'},
        {id:'23-file-write', topic:'Q5 – File writing algorithm', page:21, skill:'Read file handling',
          code:`num = input("enter a number")\nvalue = doCheck(num)\ntxtfile = openWrite("storedvalues.txt")\ntxtfile.writeLine(num)\ntxtfile.writeLine(value)\ntxtfile.close()`,
          question:'Why should the file be closed at the end?',
          options:['To ensure data is saved and release the file resource','To delete the file','To call doCheck again','To convert the file to binary'], answer:0,
          worked:['The algorithm opens a file for writing.','It writes two values.','Closing the file completes the write operation and releases the file.'],
          fact:'File handling algorithms should open, read/write, and then close the file.'},
        {id:'23-stack-expression', topic:'Q2 – Stack algorithm trace', page:7, skill:'Trace stack actions',
          code:`Input: 9 3 A E\nA: pop two, add them, push result\nE: pop one and output it`,
          question:'What is output?',
          options:['3','9','12','27'], answer:2,
          worked:['Push 9, then push 3.','A pops 3 and 9, adds them to get 12, and pushes 12.','E pops and outputs 12.'],
          fact:'A stack is LIFO: the last value pushed is the first value popped.'},
        {id:'23-stack-underflow', topic:'Q2 – Stack error', page:8, skill:'Identify runtime problem',
          code:`Input: 4 2 S A E\nS: pop two, subtract first popped from second popped, push result\nA: pop two, add, push result`,
          question:'What problem occurs?',
          options:['Stack underflow because A tries to pop two values when only one is present','Stack overflow because too many values are pushed','The loop stops too early','The values are sorted'], answer:0,
          worked:['4 and 2 are pushed.','S pops both and pushes one result.','Only one value remains.','A needs two values, so it tries to pop from an empty stack.'],
          fact:'Stack underflow occurs when a program tries to pop from an empty stack.'},
        {id:'23-html-ul', topic:'Q4 – HTML list', page:16, skill:'Complete HTML',
          code:`<h1>Robot prime directives</h1>\n_____\n  <li>Serve the company trust</li>\n  <li>Protect data</li>\n  <li>Uphold standards</li>\n_____`,
          question:'Which tags complete the bulleted list?',
          options:['<ul> and </ul>','<p> and </p>','<a> and </a>','<form> and </form>'], answer:0,
          worked:['li elements are list items.','A bulleted list is an unordered list.','The container tags are <ul> and </ul>.'],
          fact:'HTML uses nested tags: list items must sit inside a list container such as ul or ol.'},
        {id:'23-css-h1', topic:'Q4 – CSS selector', page:17, skill:'Read CSS rule',
          code:`h1 {\n  color: white;\n  background-color: red;\n}`,
          question:'What does this CSS rule do?',
          options:['Formats all h1 text as white with a red background','Formats all paragraphs as red text','Creates a hyperlink','Submits a form'], answer:0,
          worked:['h1 is the selector.','color controls text colour.','background-color controls the background of the h1 element.'],
          fact:'In CSS, selector { property: value; } applies styling to matching HTML elements.'},
        {id:'23-sql-delete', topic:'Q4 – SQL DELETE', page:19, skill:'Read SQL deletion',
          code:`DELETE FROM TblAccessLog\nWHERE UserType = "NotNeeded"`,
          question:'What records are removed?',
          options:['Only records where UserType is NotNeeded','All records in the table','Only Admin users','Only the DateAccessed field'], answer:0,
          worked:['DELETE FROM names the table.','WHERE filters the records to delete.','Only rows matching UserType = "NotNeeded" are deleted.'],
          fact:'Without a WHERE clause, DELETE would remove every record from the table.'},
        {id:'23-pseudocode-loop', topic:'Q2 – Do-until loop', page:7, skill:'Read loop end condition',
          code:`do\n  value = input("Enter a value")\n  ...\nuntil value == "E"`,
          question:'When does this loop stop?',
          options:['After value E has been entered and processed','Before any input is taken','After exactly 10 repeats','When the stack is full'], answer:0,
          worked:['A do loop checks its condition at the end.','The body runs, then value is checked.','It stops once value equals "E".'],
          fact:'A do-until loop is a post-condition loop, so it runs at least once.'}
      ]
    },
    {
      id: '2022', title: 'H446/01 June 2022', pdf: 'pdfs/H44601 Computer Systems June 2022.pdf',
      questions: [
        {id:'22-mystery', topic:'Q5 – Function trace', page:18, skill:'Trace function output',
          code:`function mystery(x, y)\n  if x < y then\n    return x * 2 + y\n  else\n    return x + y * 2\n  endif\nendfunction`,
          question:'Using this structure, what should you do first when tracing mystery(10,20)?',
          options:['Check the condition x < y','Multiply every value by 2 immediately','Ignore the parameters','Run both branches'], answer:0,
          worked:['The parameters x=10 and y=20 are substituted first.','The condition x < y decides which branch runs.','Only one branch is followed.'],
          fact:'For selection, always evaluate the condition before choosing the branch.'},
        {id:'22-count-capitals', topic:'Q5 – Count capitals', page:21, skill:'Complete return',
          code:`function countCapitals(text)\n  capCount = 0\n  for x = 0 to text.length-1\n    ...\n  next x\n  ______\nendfunction`,
          question:'Which final line should return the number of capital letters?',
          options:['return capCount','print text','capCount = 0','return text.length'], answer:0,
          worked:['capCount stores how many capital letters have been found.','A function gives a value back using return.','Returning text.length would return the total number of characters, not capitals.'],
          fact:'A function should return the variable that stores the result it has calculated.'},
        {id:'22-sql-adverts', topic:'Q2 – SQL SELECT', page:8, skill:'Select fields and condition',
          code:`Membership(Username, FirstName, PackageType)\nPackage(PackageType, Adverts)`,
          question:'Which fields must the final query return for customers who see adverts?',
          options:['Username and FirstName','PackageType and Adverts only','CostPerMonth only','Every field from both tables'], answer:0,
          worked:['The question asks for Username and FirstName fields.','Adverts is used as a condition, not as an output field.','PackageType is needed to link the tables.'],
          fact:'SELECT controls which fields are returned; WHERE controls which records are included.'},
        {id:'22-class-video', topic:'Q2 – OOP attributes', page:12, skill:'Identify private attributes',
          code:`class video\n  private name\n  private views\n  private starrating\nendclass`,
          question:'Why are these attributes marked private?',
          options:['To protect the object state and control access through methods','To make them global variables','To stop the constructor running','To delete them after one use'], answer:0,
          worked:['Private attributes cannot normally be accessed directly from outside the class.','Methods can control how values are read or changed.','This supports encapsulation.'],
          fact:'Encapsulation means keeping data and methods together while controlling access to internal data.'},
        {id:'22-updateviews', topic:'Q2 – OOP method', page:13, skill:'Choose method body',
          code:`public procedure updateviews()\n  ______\nendprocedure`,
          question:'Which line correctly increases the views attribute by one?',
          options:['views = views + 1','views = 1','views + 1','return views + 1'], answer:0,
          worked:['The old value must be read.','1 is added.','The result is stored back into views.'],
          fact:'An assignment is needed; an expression on its own does not update a variable.'},
        {id:'22-compilation', topic:'Q5 – Compilation stages', page:20, skill:'Match action to stage',
          code:`Object code is created`,
          question:'Which stage of compilation creates object code?',
          options:['Code generation','Lexical analysis','Syntax analysis','Code optimisation'], answer:0,
          worked:['Code generation converts the checked structure into low-level/object code.','Lexical analysis tokenises.','Syntax analysis checks grammar.'],
          fact:'Code optimisation improves efficiency without changing what the program does.'},
        {id:'22-acid-lock', topic:'Q2 – Record locking logic', page:10, skill:'Read concurrency concept',
          code:`Transaction A wants to update a record.\nTransaction B wants to update the same record at the same time.\nRecord locking is enabled.`,
          question:'What should record locking do?',
          options:['Allow only one transaction to access/modify the record at a time','Let both overwrite each other','Delete the record','Convert the record to a file'], answer:0,
          worked:['Isolation means concurrent transactions should not interfere.','Locking prevents another transaction changing the same record at the same time.','This helps avoid lost updates.'],
          fact:'ACID isolation means concurrent transactions behave as if they happened one after another.'},
        {id:'22-tcp-app', topic:'Q6 – TCP/IP application layer', page:25, skill:'Read protocol layer role',
          code:`Encrypted messaging program\nTCP/IP stack\nApplication layer`,
          question:'Which task best fits the application layer?',
          options:['Providing protocols/services used by the messaging application','Sending electrical signals on the local network','Choosing the next physical cable','Storing data in cache'], answer:0,
          worked:['The application layer provides network services for user applications.','For messaging this may include protocols for sending/receiving messages and encryption-related application behaviour.','Lower layers handle addressing, routing and physical transmission.'],
          fact:'TCP/IP layers divide communication into manageable stages.'}
      ]
    }
  ]
};
